### ISSUE TITLE
Add section to view completed orders

### ISSUE THREAD

**Issue by robinske** [twilio-labs/twilio-mixologist#19]
(Instead of having them disappear completely). When they disappear from the view it's hard to remember what was just made.

Barista requested feature!

**Comment by dkundel** [comment]
Hmm this would require some changes as they are actually deleted from that Sync List but I might be able to cross correlate them from the AllOrders list that keeps track of the stats.

**Comment by philnash** [comment]
Rather than cross correlate, why not include a "complete" property to an order that can be used to filter across from the regular orders panel to a completed panel?

**Comment by IObert** [comment]
Done in the latest version of the project
