### ISSUE TITLE
Add ping or noise when order comes in to help notify baristas

### ISSUE THREAD

**Issue by robinske** [twilio-labs/twilio-mixologist#21]
Especially when there are a lot of in person orders, it can be easy to ignore the tablet.

Barista requested feature!

**Comment by dkundel** [comment]
That's an interesting one. I see to potential solutions for this. One would be to use the Notification API of the browser to trigger these (the tablets should support that) and the other one would be to trigger a custom audio sound. I'll think about this one :)
