### ISSUE TITLE
A way to turn down orders of multiple coffees

### ISSUE THREAD

**Issue by philnash** [twilio-labs/twilio-mixologist#31]
Using the app in wework and some people are ordering for their team in one message.

Can we figure out if an order is for more than one coffee and trigger a reply that tells users that they can only order one at a time?

**Comment by philnash** [comment]
Hmmm... or maybe we need a way to cancel an order with a specific message. This would be more useful generally.

**Comment by dkundel** [comment]
You can cancel an order by writing 'cancel order'. For the other thing, maybe once we have a better Natural Language detection. I don't think trying to hard code this, will properly solve this. Alternatively the original message is always being displayed in the app. So you can go "old school" and teach the baristas.

Cheers,
Dominik

**Comment by philnash** [comment]
Ah, this was more on behalf of the barista. If there was a way to cancel with a specific message rather than the generic one, then the cancellation experience would be a lot better.
