### ISSUE TITLE
Run UI independent of API

### ISSUE THREAD

**Issue by dkundel** [twilio-labs/twilio-mixologist#4]
Most of the work here is already done but basically there should be an environment variable that when set, starts up the Node.js server without the back-end but instead makes the front-end talk to another back-end that is being specified. For this we need to slightly alter the entry part of the server as well as create a route that the front-end server contacts to ask what the actual API endpoint is.

This way we could easily write different back-ends as long as they support a certain set of endpoints for the admin interface and support the data structures used by Twilio Sync

**Comment by IObert** [comment]
It's still coupled but a NextJS app now
